### ISSUE TITLE
Web app not working (when using COPR version of ntfy)

### ISSUE THREAD

**Issue by JacksonChen666** [cyqsimon/ntfysh-spec#1]
When trying to access ntfy (or the webapp specifically), nothing shows up.

<img width="1680" alt="" src="https://user-images.githubusercontent.com/50755746/209349953-3e75850a-7ecd-4644-b06e-210bdd30da51.png">

[requests.har.zip](https://github.com/cyqsimon/ntfysh-spec/files/10295567/ntfy.jacksonchen666.com_Archive.22-12-23.15-15-38.har.zip)

If ntfy was setup not to serve the webapp, it works as expected in that configuration.

My ntfy instance is still fundamentally functional (the notifications part works)

**Comment by cyqsimon** [comment]
Huh, interesting. I never had need for the web app, so this build script actually never installed the files necessary.

Truth be told, it's not very well documented where the web files should be installed to. I guess I will go take a look at the `.deb`/`.rpm` packages provided in the release to see how it's done officially.

**Comment by cyqsimon** [comment]
![rpm file list](https://user-images.githubusercontent.com/28627918/209443844-1b59dede-a97f-4676-8cc6-731f9eedbe8c.png)

![deb file list](https://user-images.githubusercontent.com/28627918/209444475-8674b78b-05ee-4bf3-8610-dcee10e791bd.png)


Turns out, the web files are not packaged by the official release either. I will have to go ask the author for instructions then.

**Comment by JacksonChen666** [comment]
@cyqsimon can you check earlier versions? i haven't tested the latest release with the direct RPMs. (1.29 or something)

**Comment by cyqsimon** [comment]
> can you check earlier versions?

Can you find me a version with working web app? `.deb`, `.rpm`, anything.

Honestly I doubt you can find one, because AFAIK the packaging scripts haven't been changed in a long long while, so there's no reason it would be any different between versions.

**Comment by JacksonChen666** [comment]
@cyqsimon [release 1.29.1](https://github.com/binwiederhier/ntfy/releases/tag/v1.29.1) or [amd64 rpm](https://github.com/binwiederhier/ntfy/releases/download/v1.29.1/ntfy_1.29.1_linux_amd64.rpm) (version that i know has working webapp)

**Comment by cyqsimon** [comment]
Huh interesting. It seems like the web files are bundled into the executable; I stand corrected. I guess there are some extra flags I need to pass during build.

**Comment by cyqsimon** [comment]
Ah okay. I just need to `make web` before I `make cli-linux-server`. Should be easy enough to fix, although node dependency might give me some trouble on EL7/8.

**Comment by cyqsimon** [comment]
Okay. Fixed in `1.30.1-2`. `rawhide` build is failing, but that's due to some dependency weirdness that will probably solve itself in a few weeks.

**Comment by JacksonChen666** [comment]
can confirm the thing is now working
